site:
  title: SOGo 6 - Dev Doc
  start_page: SOGo6-DevDoc::0_intro_doc.adoc
git:
  ensure_git_suffix: false
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs/developer
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: docs/developer/build