"""Celery wrapper. The only file in the project that imports celery directly."""
from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any, TYPE_CHECKING

from celery import Celery
from celery.schedules import crontab
from celery.signals import task_failure, task_postrun, task_prerun, task_retry, task_revoked

from app.agent.jobs.Job import collected_agent_class_jobs
from app.agent.jobs.JobState import JobState
from app.agent.jobs.JobStatus import JobStatus
from app.config.settings.ProcessSetting import ProcessSetting, process_config
from app.manager.storage.StorageSource import StorageSource
from app.utils.exceptions import AggravatedException
from app.utils.logger.logger import logger_agent
from app.utils.module.importManager import import_and_instantiate_manager

if TYPE_CHECKING:
    from app.agent.jobs.Job import Job
    from app.agent.jobs.JobPersistency import JobPersistency
    from app.agent.jobs.JobRequest import JobRequest
    from app.manager.cache.ClientRedis import ClientRedis
    from app.manager.storage.ClientStorage import ClientStorage


class Agent:
    """Process-wide Celery wrapper. Kept private so swapping the framework is a local change."""

    def __init__(self, process_setting: ProcessSetting) -> None:
        self._process_setting: ProcessSetting = process_setting
        self._job_handlers: dict[str, Job] = {}
        # Holds no live connection: the DB-backed store opens one per operation (db=None),
        # so this singleton built at import never leaks a connection across the worker fork.
        self._large_store: ClientStorage = import_and_instantiate_manager(
            module_path="app.manager.storage",
            module_and_class_name=f"ClientStorage{process_setting.SOGO_P_STORAGE_TYPE.capitalize()}",
            module_args={"process_setting": process_setting, "source": StorageSource.AGENT},
        )
        self._celery: Celery = Celery(
            "sogo_agent",
            broker=process_setting.SOGO_P_REDIS_URL,
            backend=process_setting.SOGO_P_REDIS_URL,
        )
        self._celery.conf.update(
            task_acks_late=True,
            task_reject_on_worker_lost=False,
            worker_prefetch_multiplier=process_setting.SOGO_P_AGENT_WORKER_PREFETCH_MULTIPLIER,
            task_track_started=True,
            broker_transport_options={
                "visibility_timeout": process_setting.SOGO_P_AGENT_BROKER_VISIBILITY_TIMEOUT_SECONDS,
            },
            broker_connection_retry_on_startup=True,
            redis_socket_connect_timeout=30,
            redis_socket_keepalive=True,
            task_serializer="json",
            result_serializer="json",
            accept_content=["json"],
            timezone="UTC",
            enable_utc=True,
        )

    def get_large_store(self) -> ClientStorage:
        """Return the store that persists a task's large result until the user fetches it."""
        return self._large_store

    def create_job(
        self, name: str, payload: dict[str, Any], *,
        user_uid: str | None = None, eta: Any | None = None, job_id: str | None = None,
    ) -> str:
        """Publish a job to the broker.

        :param name: registered job name (matches ``JobRequest.name``).
        :type name: str
        :param payload: JSON-serialisable arguments handed to ``Job.process``.
        :type payload: dict[str, Any]
        :param user_uid: owner of the job. ``None`` for system jobs (purge, sweep...).
        :type user_uid: str | None
        :param eta: earliest time the worker may pick the job up. ``None`` means now.
        :type eta: datetime | None
        :param job_id: pre-generated id. Lets the caller persist the JobState before
            the message hits the broker, avoiding the race where the worker runs
            ``task_prerun`` while no JobState exists yet. Mapped to Celery's
            ``task_id`` kwarg on the wire.
        :type job_id: str | None
        :return: the job id, generated by Celery if not provided.
        :rtype: str
        """
        result = self._celery.send_task(
            name,
            kwargs={"payload": payload, "user_uid": user_uid},
            eta=eta,
            task_id=job_id,
        )
        logger_agent.info(
            "create_job: name=%s job_id=%s user_uid=%s eta=%s",
            name, result.id, user_uid, eta,
        )
        return str(result.id)

    def get_job_handler(self, name: str) -> Job | None:
        """Return the registered Job handler instance bound to ``name``.

        :param name: registered job name (matches ``JobRequest.name``).
        :type name: str
        :return: the handler instance, or ``None`` when no class has been
            registered under that name in this process.
        :rtype: Job | None
        """
        return self._job_handlers.get(name)

    def cancel(self, job_id: str, *, signal: str = "SIGTERM") -> None:
        """Send a control signal to a running job.

        ``JobCanceller`` calls this twice: SIGTERM for cooperative shutdown, then
        SIGKILL after the grace period if the job is still running.

        :param job_id: id of the job to interrupt.
        :type job_id: str
        :param signal: POSIX signal name. SIGTERM lets the job raise
            ``AgentJobCancelled`` and clean up; SIGKILL is unconditional.
        :type signal: str
        """
        logger_agent.info("cancel: job_id=%s signal=%s", job_id, signal)
        self._celery.control.revoke(job_id, terminate=True, signal=signal)

    def register_job_handler(self, handler: Job) -> None:
        """Register a Job handler so the worker can execute it.

        Reads name and execution metadata from ``handler.request_class`` (the
        single source of truth) and wraps the instance in a Celery task with:

        - ``soft_time_limit`` / ``time_limit`` derived from ``soft_timeout_seconds``,
        - ``autoretry_for`` taken from the Request's ``retry_for`` (defaults to any
          exception; a job can narrow it to fail fast on permanent errors),
        - ``max_retries = max_try - 1`` (the first attempt is not a retry),
        - exponential backoff with jitter, capped at 5 minutes.

        Celery preserves the task id across retries, so the ``JobState`` in Redis
        keeps tracking the same logical job through all its attempts.

        :param handler: instance of a ``Job`` subclass with a ``request_class``.
        :type handler: Job
        """
        req: type[JobRequest] = handler.request_class
        self._job_handlers[req.name] = handler
        soft_limit: int = req.soft_timeout_seconds
        max_retries: int = max(0, req.max_try - 1)

        @self._celery.task(  # pylint: disable=unused-variable
            name=req.name, bind=True,
            soft_time_limit=soft_limit, time_limit=soft_limit + 10,
            autoretry_for=req.retry_for,
            max_retries=max_retries,
            retry_backoff=True, retry_jitter=True, retry_backoff_max=300,
        )
        def _wrapper(  # pylint: disable=unused-argument
            celery_self: Any, payload: dict[str, Any], user_uid: str | None,
            schedule_name: str | None = None,
        ) -> dict[str, Any]:
            # ``schedule_name`` is set by Beat entries and read by the prerun hook (to
            # tag the JobState); the worker body itself does not use it.
            return handler._run(celery_self.request.id, payload, user_uid)  # pylint: disable=protected-access

        logger_agent.debug(
            "register_job_handler: name=%s soft_timeout=%ds max_try=%d resume=%s",
            req.name, soft_limit, req.max_try, req.resume,
        )

    def register_all_job_handlers(self) -> None:
        """Instantiate and register every class decorated with ``@agent_job``.

        Called once at boot, after each module's ``jobs`` subpackage has been
        imported so the decorators have populated the collection.
        """
        classes: list[type[Job]] = collected_agent_class_jobs()
        for cls in classes:
            self.register_job_handler(cls())
        logger_agent.info(
            "register_all_job_handlers: %d job(s) registered: %s",
            len(self._job_handlers), sorted(self._job_handlers.keys()),
        )

    def register_lifecycle_hooks(self, persistency: JobPersistency, cache: ClientRedis) -> None:  # pylint: disable=too-many-statements
        """Wire Celery signals to JobPersistency and release the concurrency lock.

        Connects five signals - prerun, postrun, retry, failure, revoked - so that
        every state transition of a job lands in Redis. ``weak=False`` keeps the
        closures alive after this method returns; otherwise Python would
        garbage-collect them and Celery would silently drop the connections.

        Terminal hooks (postrun SUCCESS/FAILURE, failure, revoked) also delete the
        concurrency lock acquired by ``ClientAgent.enqueue`` so the next job for
        the same scope can start immediately. RETRY does **not** release - the job
        is still considered active.

        Must be called once per process, before ``start_worker``.

        :param persistency: JobPersistency the closures write to.
        :type persistency: JobPersistency
        :param cache: ClientRedis used to release the concurrency lock.
        :type cache: ClientRedis
        """

        def _release_concurrency_lock(state: JobState) -> None:
            # Only jobs that took a lock (max_concurrent > 0) have one to release.
            if state.max_concurrent > 0:
                cache.delete(JobState.concurrency_lock_key(state.name, state.user_uid))

        @task_prerun.connect(weak=False)
        def _on_prerun(
            task_id: str | None = None, task: Any = None, kwargs: dict[str, Any] | None = None, **_: Any,
        ) -> None:
            # Celery passes ``task_id`` - that's the wire-level id of our job.
            job_id: str | None = task_id
            if job_id is None:
                return
            state: JobState | None = persistency.get(job_id)
            if state is None:
                # Beat-triggered jobs are sent straight to the broker, so no PENDING
                # state was persisted at enqueue. Create one now (tagged with the
                # schedule name) so periodic jobs are tracked like the rest.
                if task is None:
                    return
                kw: dict[str, Any] = kwargs or {}
                state = JobState(
                    job_id=job_id, name=task.name, status=JobStatus.STARTED,
                    user_uid=kw.get("user_uid"), date_planned=datetime.now(timezone.utc),
                    payload=kw.get("payload") or {}, schedule_name=kw.get("schedule_name"),
                )
            state.status = JobStatus.STARTED
            state.date_start = datetime.now(timezone.utc)
            state.attempts += 1
            persistency.save(state)
            logger_agent.info(
                "job_prerun: job_id=%s name=%s attempt=%d/%d",
                job_id, state.name, state.attempts, state.max_try,
            )

        @task_postrun.connect(weak=False)
        def _on_postrun(
            task_id: str | None = None, state: str | None = None, retval: Any = None, **_: Any,
        ) -> None:
            job_id: str | None = task_id
            current: JobState | None = persistency.get(job_id) if job_id else None
            if current is None:
                return
            # RETRY means another attempt is queued; leave the state to ``_on_retry``.
            if state == "RETRY":
                return
            current.date_end = datetime.now(timezone.utc)
            if current.date_start:
                current.duration_seconds = (current.date_end - current.date_start).total_seconds()
            if state == "SUCCESS":
                current.status = JobStatus.SUCCESS
                if isinstance(retval, dict):
                    current.result = retval
            elif state == "FAILURE":
                current.status = JobStatus.FAILURE
            persistency.save(current)
            _release_concurrency_lock(current)
            logger_agent.info(
                "job_postrun: job_id=%s name=%s status=%s duration=%.3fs",
                job_id, current.name, current.status.value, current.duration_seconds or 0.0,
            )

        @task_retry.connect(weak=False)
        def _on_retry(
            request: Any = None, reason: Any = None, **_: Any,
        ) -> None:
            job_id: str | None = getattr(request, "id", None) if request else None
            current: JobState | None = persistency.get(job_id) if job_id else None
            if current is None:
                return
            current.status = JobStatus.RETRY
            current.error = str(reason) if reason else None
            persistency.save(current)
            logger_agent.warning(
                "job_retry: job_id=%s name=%s attempt=%d/%d reason=%s",
                job_id, current.name, current.attempts, current.max_try, current.error,
            )

        @task_failure.connect(weak=False)
        def _on_failure(task_id: str | None = None, exception: BaseException | None = None, **_: Any) -> None:
            job_id: str | None = task_id
            # Fires only after retries are exhausted; the requeue path lives in ``_on_retry``.
            current: JobState | None = persistency.get(job_id) if job_id else None
            if current is None:
                return
            current.status = JobStatus.FAILURE
            current.error = str(exception) if exception else None
            persistency.save(current)
            _release_concurrency_lock(current)
            logger_agent.error(
                "job_failure: job_id=%s name=%s error=%s",
                job_id, current.name, current.error,
            )

        @task_revoked.connect(weak=False)
        def _on_revoked(request: Any = None, **_: Any) -> None:
            job_id: str | None = getattr(request, "id", None) if request else None
            current: JobState | None = persistency.get(job_id) if job_id else None
            if current is None:
                return
            current.status = JobStatus.CANCELED
            current.date_end = datetime.now(timezone.utc)
            if current.date_start:
                current.duration_seconds = (current.date_end - current.date_start).total_seconds()
            persistency.save(current)
            _release_concurrency_lock(current)
            logger_agent.info("job_revoked: job_id=%s name=%s", job_id, current.name)

    def start_worker(self) -> None:
        """Run a Celery worker.

        Blocks until the worker receives a shutdown signal. Concurrency comes
        from ``ProcessSetting``. ``--without-mingle/gossip/heartbeat`` skips the
        Redis pubsub features we do not use, cutting boot time and chatter.
        """
        concurrency: int = self._process_setting.SOGO_P_AGENT_WORKER_CONCURRENCY
        argv: list[str] = [
            "worker", "-l", "INFO",
            "--concurrency", str(concurrency),
            "--without-mingle", "--without-gossip", "--without-heartbeat",
        ]
        logger_agent.info("start_worker: concurrency=%d", concurrency)
        self._celery.worker_main(argv)

    def start_beat(self) -> None:
        """Run the Celery Beat scheduler (blocking).

        Builds the periodic schedule from every registered job whose Request
        declares a ``cron``, then runs beat with its last-run state file from
        ``SOGO_P_AGENT_BEAT_SCHEDULE_PATH``. Run a SINGLE beat instance - several
        would each fire the schedule and enqueue duplicates (the entrypoint guards
        this with a Redis lock).
        """
        schedule_path: str = self._process_setting.SOGO_P_AGENT_BEAT_SCHEDULE_PATH
        schedule_dir: str = os.path.dirname(schedule_path)
        try:
            if schedule_dir:
                os.makedirs(schedule_dir, exist_ok=True)
        except OSError as exc:
            raise AggravatedException(
                f"Cannot create the beat schedule directory {schedule_dir!r}: {exc}. "
                "Provision it (writable by the agent user) or point "
                "SOGO_P_AGENT_BEAT_SCHEDULE_PATH at a writable path."
            ) from exc
        self._celery.conf.beat_schedule = self._build_beat_schedule()
        self._celery.conf.beat_schedule_filename = schedule_path
        logger_agent.info(
            "start_beat: schedule_path=%s entries=%d", schedule_path,
            len(self._celery.conf.beat_schedule),
        )
        self._celery.Beat(loglevel="INFO").run()

    def _build_beat_schedule(self) -> dict[str, dict[str, Any]]:
        """Build the Celery beat schedule from every registered Request declaring a ``cron``.

        Reads the same handler registry the worker executes from (``_job_handlers``),
        so beat never schedules a job the worker cannot run. Each periodic job becomes
        one entry keyed by its registered name; Beat enqueues it with an empty owner
        and a ``schedule_name`` tag (so the ``task_prerun`` hook can persist a JobState
        for the run). The payload comes from the Request built with no arguments - a
        periodic job takes no caller input.

        :return: mapping of job name to its beat entry (task, schedule, kwargs).
        :rtype: dict[str, dict[str, Any]]
        """
        schedule: dict[str, dict[str, Any]] = {}
        for handler in self._job_handlers.values():
            request_class: type[JobRequest] = handler.request_class
            cron: str | None = request_class.cron
            if cron is None:
                continue
            job_name: str = request_class.name
            schedule[job_name] = {
                "task": job_name,
                "schedule": self._crontab_from_string(cron),
                "kwargs": {
                    "payload": request_class().payload(),
                    "user_uid": None,
                    "schedule_name": job_name,
                },
            }
        return schedule

    @staticmethod
    def _crontab_from_string(expression: str) -> crontab:
        """Build a Celery crontab from a standard 5-field cron expression.

        Fields, in order: minute, hour, day-of-month, month, day-of-week
        (e.g. "0 2 * * *" = daily at 02:00). Each field passes through to Celery
        verbatim, so steps, ranges and lists ("*/6", "1-5", "0,30") work.

        :param expression: a 5-field cron expression.
        :type expression: str
        :return: the matching Celery crontab schedule.
        :rtype: crontab
        """
        fields: list[str] = expression.split()
        if len(fields) != 5:
            raise AggravatedException(
                f"Invalid cron expression {expression!r}: expected 5 fields "
                "(minute hour day-of-month month day-of-week)."
            )
        minute, hour, day_of_month, month_of_year, day_of_week = fields
        try:
            return crontab(
                minute=minute, hour=hour, day_of_month=day_of_month,
                month_of_year=month_of_year, day_of_week=day_of_week,
            )
        except (ValueError, KeyError) as exc:
            raise AggravatedException(f"Invalid cron expression {expression!r}: {exc}") from exc

agent: Agent = Agent(process_config)
