"""Celery wrapper. The only file in the project that imports celery directly."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, TYPE_CHECKING

from celery import Celery
from celery.signals import task_failure, task_postrun, task_prerun, task_retry, task_revoked

from app.agent.tasks.TaskStatus import TaskStatus
from app.config.settings.ProcessSetting import ProcessSetting, process_config
from app.utils.logger.logger import logger_agent

from app.agent.tasks.BaseTask import collected_agent_class_tasks

if TYPE_CHECKING:
    from app.agent.tasks.BaseTask import BaseTask
    from app.agent.tasks.TaskPersistency import TaskPersistency


class Agent:
    """Process-wide Celery wrapper. Kept private so swapping the framework is a local change."""

    def __init__(self, process_setting: ProcessSetting) -> None:
        self._process_setting: ProcessSetting = process_setting
        self._task_handlers: dict[str, BaseTask] = {}
        self._celery: Celery = Celery(
            "sogo_agent",
            broker=process_setting.SOGO_P_REDIS_URL,
            backend=process_setting.SOGO_P_REDIS_URL,
        )
        self._celery.conf.update(
            task_acks_late=True,
            task_reject_on_worker_lost=False,
            worker_prefetch_multiplier=process_setting.SOGO_P_AGENT_WORKER_PREFETCH_MULTIPLIER,
            task_track_started=True,
            broker_transport_options={
                "visibility_timeout": process_setting.SOGO_P_AGENT_BROKER_VISIBILITY_TIMEOUT_SECONDS,
            },
            broker_connection_retry_on_startup=True,
            redis_socket_connect_timeout=30,
            redis_socket_keepalive=True,
            task_serializer="json",
            result_serializer="json",
            accept_content=["json"],
            timezone="UTC",
            enable_utc=True,
        )

    def create_task(
        self, name: str, payload: dict[str, Any], *,
        user_uid: str | None = None, eta: Any | None = None, task_id: str | None = None,
    ) -> str:
        """Publish a task to the broker.

        :param name: registered task name (matches ``BaseTask.name``).
        :type name: str
        :param payload: JSON-serialisable arguments handed to ``BaseTask.process``.
        :type payload: dict[str, Any]
        :param user_uid: owner of the task. ``None`` for system tasks (purge, sweep…).
        :type user_uid: str | None
        :param eta: earliest time the worker may pick the task up. ``None`` means now.
        :type eta: datetime | None
        :param task_id: pre-generated id. Lets the caller persist the TaskState before
            the message hits the broker, avoiding the race where the worker runs
            ``task_prerun`` while no TaskState exists yet.
        :type task_id: str | None
        :return: the task id, generated by Celery if not provided.
        :rtype: str
        """
        result = self._celery.send_task(
            name,
            kwargs={"payload": payload, "user_uid": user_uid},
            eta=eta,
            task_id=task_id,
        )
        logger_agent.info(
            "create_task: name=%s task_id=%s user_uid=%s eta=%s",
            name, result.id, user_uid, eta,
        )
        return str(result.id)

    def get_task_handler(self, name: str) -> BaseTask | None:
        """Return the registered Task handler instance bound to ``name``.

        :param name: registered task name (matches ``TaskRequest.name``).
        :type name: str
        :return: the handler instance, or ``None`` when no class has been
            registered under that name in this process.
        :rtype: BaseTask | None
        """
        return self._task_handlers.get(name)

    def cancel(self, task_id: str, *, signal: str = "SIGTERM") -> None:
        """Send a control signal to a running task.

        ``TaskCanceller`` calls this twice: SIGTERM for cooperative shutdown, then
        SIGKILL after the grace period if the task is still running.

        :param task_id: id of the task to interrupt.
        :type task_id: str
        :param signal: POSIX signal name. SIGTERM lets the task raise
            ``AgentTaskCancelled`` and clean up; SIGKILL is unconditional.
        :type signal: str
        """
        logger_agent.info("cancel: task_id=%s signal=%s", task_id, signal)
        self._celery.control.revoke(task_id, terminate=True, signal=signal)

    def register_task_handler(self, handler: BaseTask) -> None:
        """Register a Task handler so the worker can execute it.

        Reads name and execution metadata from ``handler.request_class`` (the
        single source of truth) and wraps the instance in a Celery task with:

        - ``soft_time_limit`` / ``time_limit`` derived from ``soft_timeout_seconds``,
        - ``autoretry_for=(Exception,)`` so any exception triggers a retry,
        - ``max_retries = max_try - 1`` (the first attempt is not a retry),
        - exponential backoff with jitter, capped at 5 minutes.

        Celery preserves the task id across retries, so the ``TaskState`` in Redis
        keeps tracking the same logical task through all its attempts.

        :param handler: instance of a ``BaseTask`` subclass with a ``request_class``.
        :type handler: BaseTask
        """
        req = handler.request_class
        self._task_handlers[req.name] = handler
        soft_limit: int = req.soft_timeout_seconds
        max_retries: int = max(0, req.max_try - 1)

        @self._celery.task(  # pylint: disable=unused-variable
            name=req.name, bind=True,
            soft_time_limit=soft_limit, time_limit=soft_limit + 10,
            autoretry_for=(Exception,),
            max_retries=max_retries,
            retry_backoff=True, retry_jitter=True, retry_backoff_max=300,
        )
        def _wrapper(celery_self: Any, payload: dict[str, Any], user_uid: str | None) -> dict[str, Any]:
            return handler._run(celery_self.request.id, payload, user_uid)  # pylint: disable=protected-access

        logger_agent.debug(
            "register_task_handler: name=%s soft_timeout=%ds max_try=%d resume=%s",
            req.name, soft_limit, req.max_try, req.resume,
        )

    def register_all_task_handlers(self) -> None:
        """Instantiate and register every class decorated with ``@agent_task``.

        Called once at boot, after each module's ``tasks`` subpackage has been
        imported so the decorators have populated the collection.
        """
        classes = collected_agent_class_tasks()
        for cls in classes:
            self.register_task_handler(cls())
        logger_agent.info(
            "register_all_task_handlers: %d task(s) registered: %s",
            len(self._task_handlers), sorted(self._task_handlers.keys()),
        )

    def register_lifecycle_hooks(self, persistency: TaskPersistency) -> None:
        """Wire Celery signals to TaskPersistency.

        Connects four signals — prerun, postrun, failure, revoked — so that every
        state transition of a task lands in Redis. ``weak=False`` keeps the closures
        alive after this method returns; otherwise Python would garbage-collect
        them and Celery would silently drop the connections.

        Must be called once per process, before ``start_worker``.

        :param persistency: TaskPersistency the closures write to.
        :type persistency: TaskPersistency
        """

        @task_prerun.connect(weak=False)
        def _on_prerun(task_id: str | None = None, **_: Any) -> None:
            state = persistency.get(task_id) if task_id else None
            if state is None:
                return
            state.status = TaskStatus.STARTED
            state.date_start = datetime.now(timezone.utc)
            state.attempts += 1
            persistency.save(state)
            logger_agent.info(
                "task_prerun: task_id=%s name=%s attempt=%d/%d",
                task_id, state.name, state.attempts, state.max_try,
            )

        @task_postrun.connect(weak=False)
        def _on_postrun(
            task_id: str | None = None, state: str | None = None, retval: Any = None, **_: Any,
        ) -> None:
            current = persistency.get(task_id) if task_id else None
            if current is None:
                return
            # RETRY means another attempt is queued; leave the state to ``_on_retry``.
            if state == "RETRY":
                return
            current.date_end = datetime.now(timezone.utc)
            if current.date_start:
                current.duration_seconds = (current.date_end - current.date_start).total_seconds()
            if state == "SUCCESS":
                current.status = TaskStatus.SUCCESS
                if isinstance(retval, dict):
                    current.result = retval
            elif state == "FAILURE":
                current.status = TaskStatus.FAILURE
            persistency.save(current)
            logger_agent.info(
                "task_postrun: task_id=%s name=%s status=%s duration=%.3fs",
                task_id, current.name, current.status.value, current.duration_seconds or 0.0,
            )

        @task_retry.connect(weak=False)
        def _on_retry(
            request: Any = None, reason: Any = None, **_: Any,
        ) -> None:
            task_id = getattr(request, "id", None) if request else None
            current = persistency.get(task_id) if task_id else None
            if current is None:
                return
            current.status = TaskStatus.RETRY
            current.error = str(reason) if reason else None
            persistency.save(current)
            logger_agent.warning(
                "task_retry: task_id=%s name=%s attempt=%d/%d reason=%s",
                task_id, current.name, current.attempts, current.max_try, current.error,
            )

        @task_failure.connect(weak=False)
        def _on_failure(task_id: str | None = None, exception: BaseException | None = None, **_: Any) -> None:
            # Fires only after retries are exhausted; the requeue path lives in ``_on_retry``.
            current = persistency.get(task_id) if task_id else None
            if current is None:
                return
            current.status = TaskStatus.FAILURE
            current.error = str(exception) if exception else None
            persistency.save(current)
            logger_agent.error(
                "task_failure: task_id=%s name=%s error=%s",
                task_id, current.name, current.error,
            )

        @task_revoked.connect(weak=False)
        def _on_revoked(request: Any = None, **_: Any) -> None:
            task_id = getattr(request, "id", None) if request else None
            current = persistency.get(task_id) if task_id else None
            if current is None:
                return
            current.status = TaskStatus.CANCELED
            current.date_end = datetime.now(timezone.utc)
            if current.date_start:
                current.duration_seconds = (current.date_end - current.date_start).total_seconds()
            persistency.save(current)
            logger_agent.info("task_revoked: task_id=%s name=%s", task_id, current.name)

    def start_worker(self) -> None:
        """Run a Celery worker.

        Blocks until the worker receives a shutdown signal. Concurrency comes
        from ``ProcessSetting``. ``--without-mingle/gossip/heartbeat`` skips the
        Redis pubsub features we do not use, cutting boot time and chatter.
        """
        concurrency: int = self._process_setting.SOGO_P_AGENT_WORKER_CONCURRENCY
        argv: list[str] = [
            "worker", "-l", "INFO",
            "--concurrency", str(concurrency),
            "--without-mingle", "--without-gossip", "--without-heartbeat",
        ]
        logger_agent.info("start_worker: concurrency=%d", concurrency)
        self._celery.worker_main(argv)

agent: Agent = Agent(process_config)
