"""
iCalendar RFC 5545 Section 4 examples.
Source: https://icalendar.org/iCalendar-RFC-5545/4-icalendar-object-examples.html

These constants are shared across deserialization, serialization and roundtrip
tests to avoid repetition.
"""

# Example 1 - Three-day conference, UTC datetimes, single ORGANIZER
ICAL_EXAMPLE_1 = (
    "BEGIN:VCALENDAR\r\n"
    "PRODID:-//xyz Corp//NONSGML PDA Calendar Version 1.0//EN\r\n"
    "VERSION:2.0\r\n"
    "BEGIN:VEVENT\r\n"
    "DTSTAMP:19960704T120000Z\r\n"
    "UID:uid1@example.com\r\n"
    "ORGANIZER:mailto:jsmith@example.com\r\n"
    "DTSTART:19960918T143000Z\r\n"
    "DTEND:19960920T220000Z\r\n"
    "STATUS:CONFIRMED\r\n"
    "CATEGORIES:CONFERENCE\r\n"
    "SUMMARY:Networld+Interop Conference\r\n"
    "DESCRIPTION:Networld+Interop Conference\r\n"
    " and Exhibit\\nAtlanta World Congress Center\\n\r\n"
    " Atlanta\\, Georgia\r\n"
    "END:VEVENT\r\n"
    "END:VCALENDAR\r\n"
)

# Example 2 - Group meeting with VTIMEZONE (America/New_York), ATTENDEE with RSVP+ROLE+CUTYPE
ICAL_EXAMPLE_2 = (
    "BEGIN:VCALENDAR\r\n"
    "PRODID:-//RDU Software//NONSGML HandCal//EN\r\n"
    "VERSION:2.0\r\n"
    "BEGIN:VTIMEZONE\r\n"
    "TZID:America/New_York\r\n"
    "BEGIN:STANDARD\r\n"
    "DTSTART:19981025T020000\r\n"
    "TZOFFSETFROM:-0400\r\n"
    "TZOFFSETTO:-0500\r\n"
    "TZNAME:EST\r\n"
    "END:STANDARD\r\n"
    "BEGIN:DAYLIGHT\r\n"
    "DTSTART:19990404T020000\r\n"
    "TZOFFSETFROM:-0500\r\n"
    "TZOFFSETTO:-0400\r\n"
    "TZNAME:EDT\r\n"
    "END:DAYLIGHT\r\n"
    "END:VTIMEZONE\r\n"
    "BEGIN:VEVENT\r\n"
    "DTSTAMP:19980309T231000Z\r\n"
    "UID:guid-1.example.com\r\n"
    "ORGANIZER:mailto:mrbig@example.com\r\n"
    "ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;CUTYPE=GROUP:\r\n"
    " mailto:employee-A@example.com\r\n"
    "DESCRIPTION:Project XYZ Review Meeting\r\n"
    "CATEGORIES:MEETING\r\n"
    "CLASS:PUBLIC\r\n"
    "CREATED:19980309T130000Z\r\n"
    "SUMMARY:XYZ Project Review\r\n"
    "DTSTART;TZID=America/New_York:19980312T083000\r\n"
    "DTEND;TZID=America/New_York:19980312T093000\r\n"
    "LOCATION:1CP Conference Room 4350\r\n"
    "END:VEVENT\r\n"
    "END:VCALENDAR\r\n"
)

# Example 3 - Single event, multiple CATEGORIES, URI attachment, folded DESCRIPTION and ATTACH
ICAL_EXAMPLE_3 = (
    "BEGIN:VCALENDAR\r\n"
    "METHOD:xyz\r\n"
    "VERSION:2.0\r\n"
    "PRODID:-//ABC Corporation//NONSGML My Product//EN\r\n"
    "BEGIN:VEVENT\r\n"
    "DTSTAMP:19970324T120000Z\r\n"
    "SEQUENCE:0\r\n"
    "UID:uid3@example.com\r\n"
    "ORGANIZER:mailto:jdoe@example.com\r\n"
    "ATTENDEE;RSVP=TRUE:mailto:jsmith@example.com\r\n"
    "DTSTART:19970324T123000Z\r\n"
    "DTEND:19970324T210000Z\r\n"
    "CATEGORIES:MEETING,PROJECT\r\n"
    "CLASS:PUBLIC\r\n"
    "SUMMARY:Calendaring Interoperability Planning Meeting\r\n"
    "DESCRIPTION:Discuss how we can test c&s interoperability\\n\r\n"
    " using iCalendar and other IETF standards.\r\n"
    "LOCATION:LDB Lobby\r\n"
    "ATTACH;FMTTYPE=application/postscript:ftp://example.com/pub/\r\n"
    " conf/bkgrnd.ps\r\n"
    "END:VEVENT\r\n"
    "END:VCALENDAR\r\n"
)

# Example 4 - VTODO with VALARM (not a VEVENT - not supported by CalEventDeserializerIcal)
ICAL_EXAMPLE_4 = (
    "BEGIN:VCALENDAR\r\n"
    "VERSION:2.0\r\n"
    "PRODID:-//ABC Corporation//NONSGML My Product//EN\r\n"
    "BEGIN:VTODO\r\n"
    "DTSTAMP:19980130T134500Z\r\n"
    "SEQUENCE:2\r\n"
    "UID:uid4@example.com\r\n"
    "ORGANIZER:mailto:unclesam@example.com\r\n"
    "ATTENDEE;PARTSTAT=ACCEPTED:mailto:hcabot@example.com\r\n"
    "DUE:19980415T000000\r\n"
    "STATUS:NEEDS-ACTION\r\n"
    "SUMMARY:Submit Income Taxes\r\n"
    "BEGIN:VALARM\r\n"
    "ACTION:AUDIO\r\n"
    "TRIGGER;VALUE=DATE-TIME:19980403T120000Z\r\n"
    "ATTACH;FMTTYPE=audio/basic:ftp://example.com/pub/\r\n"
    " sounds/bell-01.aud\r\n"
    "END:VALARM\r\n"
    "END:VTODO\r\n"
    "END:VCALENDAR\r\n"
)

# Example 5 - VJOURNAL with long folded DESCRIPTION (not supported by CalEventDeserializerIcal)
ICAL_EXAMPLE_5 = (
    "BEGIN:VCALENDAR\r\n"
    "VERSION:2.0\r\n"
    "PRODID:-//ABC Corporation//NONSGML My Product//EN\r\n"
    "BEGIN:VJOURNAL\r\n"
    "DTSTAMP:19970324T120000Z\r\n"
    "UID:uid5@example.com\r\n"
    "ORGANIZER:mailto:jsmith@example.com\r\n"
    "STATUS:DRAFT\r\n"
    "CLASS:PUBLIC\r\n"
    "CATEGORIES:Project Report, XYZ, Weekly Meeting\r\n"
    "DESCRIPTION:Project xyz Review Meeting Minutes\\n\r\n"
    " Agenda\\n1. Review of project version 1 requirements\\n2.\r\n"
    "  Follow up on staff  recruitment for the project\\n3. Pre\r\n"
    " sentation of project budget.\\n4. Presentation of project\r\n"
    "  schedule.\\nSigned: JohnSmith, January 20, 1997\r\n"
    "END:VJOURNAL\r\n"
    "END:VCALENDAR\r\n"
)

# Example 6 - VFREEBUSY request/response (not supported by CalEventDeserializerIcal)
ICAL_EXAMPLE_6 = (
    "BEGIN:VCALENDAR\r\n"
    "VERSION:2.0\r\n"
    "PRODID:-//ABC Corporation//NONSGML My Product//EN\r\n"
    "METHOD:REQUEST\r\n"
    "BEGIN:VFREEBUSY\r\n"
    "DTSTAMP:19970901T115957Z\r\n"
    "DTSTART:19971001T000000Z\r\n"
    "DTEND:19971002T000000Z\r\n"
    "FREEBUSY:19971001T180000Z/19971001T190000Z\r\n"
    "FREEBUSY:19971001T080000Z/19971001T090000Z\r\n"
    "FREEBUSY:19971001T160000Z/19971001T180000Z\r\n"
    "UID:uid6@example.com\r\n"
    "ORGANIZER:mailto:jane_doe@example.com\r\n"
    "ATTENDEE:mailto:john_public@example.com\r\n"
    "COMMENT:This iCalendar file contains busy time information for\r\n"
    " the next day.\r\n"
    "END:VFREEBUSY\r\n"
    "END:VCALENDAR\r\n"
)
