mail_privileged_group = vmail

mail_uid = vmail
mail_gid = vmail

mail_driver = maildir
mail_path = /var/mail/%{user | username}

namespace inbox {
  inbox = yes
  separator = /
  prefix = INBOX/
}

namespace shared {
  type = shared
  separator = /
  prefix = shared/$user/
  mail_path = /var/mail/%{owner_user | username}
  mail_index_private_path = /var/mail/%{user | username}/shared/%{owner_user | username}
  subscriptions = no
  list = children
}

mail_plugins {
  acl = yes
  quota = yes
}

protocol imap {
  mail_plugins {
    imap_acl = yes
    imap_quota = yes
  }
}


acl_driver = vfile

acl_sharing_map {
  dict file {
    path = /etc/dovecot/sharing.db
  }
}