mail_privileged_group = vmail

mail_uid = vmail
mail_gid = vmail

mail_driver = maildir
mail_path = /var/mail/%{user | username}

namespace inbox {
  inbox = yes
  prefix = INBOX.
}

namespace second {
  list = no
  prefix = #foo
}

mail_plugins {
  acl = yes
  quota = yes
}

protocol imap {
  mail_plugins {
    imap_acl = yes
    imap_quota = yes
  }
}


acl_driver = vfile

acl_sharing_map {
  dict file {
    path = /etc/dovecot/sharing.db
  }
}