mail_location = maildir:/var/mail/%n
namespace inbox {
  inbox = yes
#  prefix = INBOX.
}
mail_privileged_group = mail
protocol !indexer-worker {
}

# namespace {
#   type = shared
#   # separator = /
#   prefix = shared/%%n/
#   # a) Per-user seen flags. Maildir indexes are shared. (INDEXPVT requires v2.2+)
#   location = maildir:%%h/Maildir:INDEXPVT=~/Maildir/shared/%%u
#   # b) Per-user seen flags. Maildir indexes are not shared. If users have direct filesystem level access to their mails, this is a safer option:
#   #location = maildir:%%h/Maildir:INDEX=~/Maildir/shared/%%u:INDEXPVT=~/Maildir/shared/%%u
#   subscriptions = no
#   list = children
# }

# Enable internal ACL support
mail_plugins = acl

# Enable the IMAP ACL commands
protocol imap {
  mail_plugins = $mail_plugins imap_acl
}

plugin {
  acl = vfile
  acl_shared_dict = file:/etc/dovecot/sharing.db
}