name: sogo

services:
  redis:
    image: redis:8
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf

  server:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile.devcontainer
    ports:
      - "5000:5000"
    user: "1000:1000"
    # command: poetry run start --host='0.0.0.0'
    command: tail -f /dev/null
    environment:
      SOGO_P_REDIS_URL: redis://sogo:sogo@redis:6379
      SECRET_KEY: "29630f23ca7c8557c75704935b6aa14a39ff28c437fcdbc10a370a4d461d0f52"
      SOGO_P_SECRET: "bookshop's spangling fakir licencing"
      SOGO_P_VOUCHER_SECRET: "dsqQHJD7dsq75aaadsqQHJD7dsq75aaa"
      SOGO_AES_ENC_KEY: "A9fK2QxM7eR3PZLwH6Jd8sC4T5mNByU"
      SOGO_P_DB_USER: sogo
      SOGO_P_DB_PASS: sogo
      SOGO_P_DB_HOST: postgresql
      SOGO_P_DB_TYPE: PostgreSQL
      # SOGO_P_DB_USER: sogo
      # SOGO_P_DB_PASS: sogo
      # SOGO_P_DB_HOST: mariadb
      # SOGO_P_DB_PORT: 3307
      # SOGO_P_DB_TYPE: MySQL
    volumes:
      - ..:/workspace
      - ./conf/sogo/process.conf:/etc/sogo/process.conf:ro
    depends_on:
      - redis

  #https://github.com/docker-library/docs/blob/master/postgres/README.md
  postgresql:
    image: postgres:17-bookworm
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./conf/db/init-sogo-postgres.db.sql:/docker-entrypoint-initdb.d/init-sogo-db.sql

  mariadb:
    image: mariadb:12
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 3307:3306
    volumes:
      - ./conf/db/init-sogo-mysql.db.sql:/docker-entrypoint-initdb.d/init-sogo-db.sql

  openldap:
    image: registry.alinto.net:5443/alinto/sogo6/openldap:2.6
    restart: unless-stopped
    ports:
      - "390:390"
    environment:
      LDAP_PORT_NUMBER: 390
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: password
      LDAP_BIND_PASSWORD: password
      LDAP_ROOT: dc=example,dc=org
      LDAP_ADMIN_DN: cn=admin,dc=example,dc=org
      LDAP_CUSTOM_LDIF_DIR: /ldifs
      LDAP_EXTRA_SCHEMAS: cosine,inetorgperson,nis,custom
    #BITNAMI_DEBUG: true
    volumes:
      - ./conf/ldap/users.ldif:/ldifs/users.ldif
      - ./conf/ldap/schemas/custom.schema:/opt/bitnami/openldap/etc/schema/custom.schema
      - ./conf/ldap/schemas/custom.ldif:/opt/bitnami/openldap/etc/schema/custom.ldif

  dovecot:
    build:
      context: ./conf/dovecot/
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - openldap
    ports:
      - "143:143"
      - "993:993"
      - "4190:4190"
      - "24:24"
    volumes:
      - sogo6-mail-data:/var/mail
      - sogo6-sieve-data:/var/sieve
      - ./conf/dovecot:/etc/dovecot

volumes:
  # sogo6-postgres:
  sogo6-mail-data:
  sogo6-sieve-data: # sogo6-mysql-data:
