#base debian bookworm
FROM python:3.13-slim


#    libldap2-dev libsasl2-dev ldap-utils \
RUN apt-get update && apt-get install -y \
    build-essential curl git \
    libldap2-dev libsasl2-dev \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry

WORKDIR /workspace

COPY ../ /workspace/ 

RUN poetry lock && poetry install

#RUN poetry run start --host="0.0.0.0"
# Make port 5000 available to the world outside this container
EXPOSE 5000