#base debian bookworm
FROM python:3.14-slim

RUN apt update && apt install -y sudo

# The standard user with which vscode-server will be executed
ENV DEBIAN_FRONTEND=noninteractive
ARG USERNAME=quentin
ARG WORKSPACE=/workspace
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG NODE_VERSION=22

RUN groupadd --system --gid "${GROUP_ID}" "${USERNAME}" && \
    useradd --system --create-home --uid "${USER_ID}" --gid "${GROUP_ID}" "${USERNAME}" && \
    echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/${USERNAME}" && \
    chmod 0440 "/etc/sudoers.d/${USERNAME}"

RUN mkdir -p ${WORKSPACE} && chown -R ${USERNAME}:${USERNAME} ${WORKSPACE}

USER 1000:1000

RUN echo "Install basic package"
RUN sudo apt install -y \
    git \
    openssh-client \
    curl \
    procps

RUN echo "Install extra packages for python libraries"
RUN sudo apt install -y \
    build-essential curl git \
    libldap2-dev libsasl2-dev \
    libpq5 \
    && sudo rm -rf /var/lib/apt/lists/*

RUN echo "Give the right to write the sogo log directory"
RUN sudo install -o ${USERNAME} -g ${USERNAME} -m 750 -d /var/log/sogo

RUN echo "Create the Agent Beat schedule directory writable by the application user"
RUN sudo install -o ${USERNAME} -g ${USERNAME} -m 750 -d /var/celery


WORKDIR /workspace
COPY ../ /workspace/ 
#RUN chown -R ${USERNAME}:${USERNAME} ${WORKSPACE}

RUN echo "Install NodeJS"
RUN sudo curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | sudo -E bash - && \
    sudo apt install -y nodejs 

RUN echo "Install poetry and the project"
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/home/${USERNAME}/.local/bin:$PATH"
RUN sudo rm -rf .poetry
RUN poetry install

# RUN echo "install antora"
# RUN node -e "fs.writeFileSync('package.json', '{}')"
# RUN npm i -D -E antora


#RUN poetry run start --host="0.0.0.0"
# Make port 5000 available to the world outside this container
EXPOSE 5000