= SOGo 6 - Configuration

SOGo 6 can be configured extensively to set the behavior of the webmail and what a user can or cannot do.

[WARNING]
====
In this documentation you will often see the word `domain`. In SOGo's context, it means the domain of the user's mail.

E.g.:

* Your SOGo is available on: **https://my.company.nu**
* User 1 connects with user1@**company.nu**, the domain from SOGo point of view is **company.nu**
* User 2 connects with user1@**external.eu**, the domain from SOGo point of view is **external.eu**

SOGo's domain only refers to the user's mail domain, it doesn't know about its own URL or frontend domain.
====

[NOTE]
====
Only the API server/backend of SOGo 6 has a configuration, the only setting of the UI/frontend being the URL of the backend.
URL used by the user's browser.
====

There are two kinds of settings: the one mandatory to run the backend application, called
process settings, provided in ENV or a file; and the one stored in the database to configure all the rest.

== Process Settings

The *process settings* are mandatory to run the API server and are meant to set once, each modification needs a restart of
SOGo 6 to be accounted for. They are provided either by ENV or a file.

== Systems, domains and rules settings.

These settings are stored in the database, a modification of them does not need to restart SOGo 6.
They set the behavior of the webmail and the external services like the mail server, the user source...

[NOTE]
====
When they're empty, which happens at the first install, SOGo 6 can run but not operate correctly as
it doesn't know where the user source is, the IMAP server...

However, you can easily set them up at the installation or deployment by providing a configuration file that will fill up the database at first install.
====

=== Systems settings

Settings that affect all the webmail whatever the user

=== Domains settings

Settings that affect only users of a said domain. You have a mandatory `default_domain_settings` that sets the settings for all users by default, except if
a setting has been defined for its domain.

[NOTE]
====
E.g: +
If you want all your users to have the same domain settings, only fill up the `default_domain_settings`. If you want the user with domain *@foo.bar* to 
have a different IMAP server than the others, you will just have to set the IMAP config for the domain *@foo.bar*. All other settings for *@foo.bar* will
fall back to `default_domain_settings`
====

=== Rules settings

It's the same as domain settings, but instead of defining custom settings for one domain, you define custom settings for several domains at once.

[WARNING]
====
Not Implemented for alpha
====

=== Precedences

The settings applied to a user according to its mail's domain are:

domain settings > rule settings > default_domain_settings
