from app.config.settings.DomainSettings import UserSourceSettings, AuthSettings, CalendarContactSettings, MailSettings, UserModuleSettings
from app.config.settings.DynamicFormSettings import create_dynamic_dict_for_settings


a = UserSourceSettings()
b = AuthSettings()
c = CalendarContactSettings()
d = MailSettings()
e = UserModuleSettings()
myresult = create_dynamic_dict_for_settings(a)
print("")
print("")
print(myresult)
myresult = create_dynamic_dict_for_settings(b)
print("")
print("")
print(myresult)
myresult = create_dynamic_dict_for_settings(c)
print("")
print("")
print(myresult)
myresult = create_dynamic_dict_for_settings(d)
print("")
print("")
print(myresult)
myresult = create_dynamic_dict_for_settings(e)
print("")
print("")
print(myresult)
